model:
    module: core.model
    class: ProtoNet
    Params:
        x_dim: 1
        hid_dim: 64
        z_dim: 64

loss:
    module: core.loss
    class: PrototypicalLoss

optim:
    module: torch.optim
    class: Adam
    Params:
        params: model.parameters()
        lr: 0.001
        betas: (0.9, 0.999)
        eps: 1e-08
        weight_decay: 1e-4
        amsgrad: True

lr_scheduler:
    module: torch.optim.lr_scheduler
    class: StepLR
    Params:
        optimizer: optimizer
        step_size: 30
        gamma: 0.1
        last_epoch: -1
        verbose: False

data:
    dataset:
        train:
            module: torchvision.datasets
            class: ImageFolder
            Params:
                image_dir: '''./dataset/train'''
                image_pattern: '''*.jpg'''
        valid:
            module: torchvision.datasets
            class: ImageFolder
            Params:
                image_dir: '''./dataset/val'''
                image_pattern: '''*.jpg'''
    dataloader:
        train:
            module: torch.utils.data
            class: DataLoader
            Params:
                dataset: train_dataset
        valid:
            module: torch.utils.data
            class: DataLoader
            Params:
                dataset: val_dataset